apiVersion: v1
kind: Service
metadata:
  name: codepub-service
spec:
  selector:
    app: codepub-service
  type: NodePort
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: codepub-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: codepub-service
  template:
    metadata:
      labels:
        app: codepub-service
    spec:
      containers:
        - name: codepub
          image: legendzzzaioi/codepub-service:v1
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          resources:
            requests:
              cpu: "100m"
              memory: "100Mi"
            limits:
              cpu: "800m"
              memory: "1000Mi"